### ISSUE TITLE
Enhancment

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SSSMobileApp#2]
2)	Make sure data filled in is not lost on automatic logout

**Comment by Technotsm** [comment]
Dear Team Members,
Please update on the above enhancements.

**Comment by serviceproviderpk** [comment]
2- Automatic logout feature is implemented.  if system remain idle for 10 mints. automatic logout will work now.

but auto save feature is time taking task. we will do it later on as enhancement. 

Thanks,
